/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Coin = IDL.Record({
  'change24h' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'volume24h' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TradeResult = IDL.Variant({ 'win' : IDL.Null, 'lose' : IDL.Null });
export const TradeDirection = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
});
export const BinaryTrade = IDL.Record({
  'id' : IDL.Nat,
  'result' : TradeResult,
  'direction' : TradeDirection,
  'coinSymbol' : IDL.Text,
  'profitLoss' : IDL.Float64,
  'durationSeconds' : IDL.Nat,
  'timestamp' : IDL.Int,
  'amount' : IDL.Float64,
  'profitPercent' : IDL.Float64,
});
export const OrderKind = IDL.Variant({
  'limit' : IDL.Float64,
  'market' : IDL.Null,
});
export const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const OrderConfirmation = IDL.Record({
  'coinSymbol' : IDL.Text,
  'totalCost' : IDL.Float64,
  'orderKind' : OrderKind,
  'orderType' : OrderType,
  'timestamp' : IDL.Int,
  'price' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const OrderRequest = IDL.Record({
  'coinSymbol' : IDL.Text,
  'orderKind' : OrderKind,
  'orderType' : OrderType,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBalance' : IDL.Func([IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllCoins' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoin' : IDL.Func([IDL.Text], [Coin], ['query']),
  'getMyBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getMyBinaryTrades' : IDL.Func([], [IDL.Vec(BinaryTrade)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderConfirmation)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeBinaryTrade' : IDL.Func(
      [IDL.Text, TradeDirection, IDL.Nat, IDL.Float64],
      [BinaryTrade],
      [],
    ),
  'placeOrder' : IDL.Func([OrderRequest], [OrderConfirmation], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCoins' : IDL.Func([IDL.Text], [IDL.Vec(Coin)], ['query']),
  'updateUsername' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Coin = IDL.Record({
    'change24h' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'volume24h' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TradeResult = IDL.Variant({ 'win' : IDL.Null, 'lose' : IDL.Null });
  const TradeDirection = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const BinaryTrade = IDL.Record({
    'id' : IDL.Nat,
    'result' : TradeResult,
    'direction' : TradeDirection,
    'coinSymbol' : IDL.Text,
    'profitLoss' : IDL.Float64,
    'durationSeconds' : IDL.Nat,
    'timestamp' : IDL.Int,
    'amount' : IDL.Float64,
    'profitPercent' : IDL.Float64,
  });
  const OrderKind = IDL.Variant({ 'limit' : IDL.Float64, 'market' : IDL.Null });
  const OrderType = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const OrderConfirmation = IDL.Record({
    'coinSymbol' : IDL.Text,
    'totalCost' : IDL.Float64,
    'orderKind' : OrderKind,
    'orderType' : OrderType,
    'timestamp' : IDL.Int,
    'price' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const OrderRequest = IDL.Record({
    'coinSymbol' : IDL.Text,
    'orderKind' : OrderKind,
    'orderType' : OrderType,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBalance' : IDL.Func([IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllCoins' : IDL.Func([], [IDL.Vec(Coin)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoin' : IDL.Func([IDL.Text], [Coin], ['query']),
    'getMyBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getMyBinaryTrades' : IDL.Func([], [IDL.Vec(BinaryTrade)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderConfirmation)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeBinaryTrade' : IDL.Func(
        [IDL.Text, TradeDirection, IDL.Nat, IDL.Float64],
        [BinaryTrade],
        [],
      ),
    'placeOrder' : IDL.Func([OrderRequest], [OrderConfirmation], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCoins' : IDL.Func([IDL.Text], [IDL.Vec(Coin)], ['query']),
    'updateUsername' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };