/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BinaryTrade {
  'id' : bigint,
  'result' : TradeResult,
  'direction' : TradeDirection,
  'coinSymbol' : string,
  'profitLoss' : number,
  'durationSeconds' : bigint,
  'timestamp' : bigint,
  'amount' : number,
  'profitPercent' : number,
}
export interface Coin {
  'change24h' : number,
  'marketCap' : number,
  'name' : string,
  'volume24h' : number,
  'price' : number,
  'symbol' : string,
}
export interface OrderConfirmation {
  'coinSymbol' : string,
  'totalCost' : number,
  'orderKind' : OrderKind,
  'orderType' : OrderType,
  'timestamp' : bigint,
  'price' : number,
  'amount' : number,
}
export type OrderKind = { 'limit' : number } |
  { 'market' : null };
export interface OrderRequest {
  'coinSymbol' : string,
  'orderKind' : OrderKind,
  'orderType' : OrderType,
  'amount' : number,
}
export type OrderType = { 'buy' : null } |
  { 'sell' : null };
export type TradeDirection = { 'long' : null } |
  { 'short' : null };
export type TradeResult = { 'win' : null } |
  { 'lose' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBalance' : ActorMethod<[number], undefined>,
  'deductBalance' : ActorMethod<[number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllCoins' : ActorMethod<[], Array<Coin>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoin' : ActorMethod<[string], Coin>,
  'getMyBalance' : ActorMethod<[], number>,
  'getMyBinaryTrades' : ActorMethod<[], Array<BinaryTrade>>,
  'getMyOrders' : ActorMethod<[], Array<OrderConfirmation>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeBinaryTrade' : ActorMethod<
    [string, TradeDirection, bigint, number],
    BinaryTrade
  >,
  'placeOrder' : ActorMethod<[OrderRequest], OrderConfirmation>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCoins' : ActorMethod<[string], Array<Coin>>,
  'updateUsername' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];