/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BinaryTrade {
    id: bigint;
    result: TradeResult;
    direction: TradeDirection;
    coinSymbol: string;
    profitLoss: number;
    durationSeconds: bigint;
    timestamp: bigint;
    amount: number;
    profitPercent: number;
}
export interface Coin {
    change24h: number;
    marketCap: number;
    name: string;
    volume24h: number;
    price: number;
    symbol: string;
}
export type OrderKind = {
    __kind__: "limit";
    limit: number;
} | {
    __kind__: "market";
    market: null;
};
export interface OrderConfirmation {
    coinSymbol: string;
    totalCost: number;
    orderKind: OrderKind;
    orderType: OrderType;
    timestamp: bigint;
    price: number;
    amount: number;
}
export interface UserProfile {
    name: string;
}
export interface OrderRequest {
    coinSymbol: string;
    orderKind: OrderKind;
    orderType: OrderType;
    amount: number;
}
export enum OrderType {
    buy = "buy",
    sell = "sell"
}
export enum TradeDirection {
    long_ = "long",
    short_ = "short"
}
export enum TradeResult {
    win = "win",
    lose = "lose"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBalance(amount: number): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllCoins(): Promise<Array<Coin>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoin(symbol: string): Promise<Coin>;
    getMyBalance(): Promise<number>;
    getMyBinaryTrades(): Promise<Array<BinaryTrade>>;
    getMyOrders(): Promise<Array<OrderConfirmation>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    placeBinaryTrade(coinSymbol: string, direction: TradeDirection, durationSeconds: bigint, amount: number): Promise<BinaryTrade>;
    placeOrder(req: OrderRequest): Promise<OrderConfirmation>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCoins(searchTerm: string): Promise<Array<Coin>>;
    updateUsername(newName: string): Promise<void>;
}
import type { BinaryTrade as _BinaryTrade, OrderConfirmation as _OrderConfirmation, OrderKind as _OrderKind, OrderRequest as _OrderRequest, OrderType as _OrderType, TradeDirection as _TradeDirection, TradeResult as _TradeResult, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBalance(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBalance(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllCoins(): Promise<Array<Coin>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoins();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoin(arg0: string): Promise<Coin> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoin(arg0);
            return result;
        }
    }
    async getMyBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalance();
            return result;
        }
    }
    async getMyBinaryTrades(): Promise<Array<BinaryTrade>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBinaryTrades();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBinaryTrades();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<OrderConfirmation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeBinaryTrade(arg0: string, arg1: TradeDirection, arg2: bigint, arg3: number): Promise<BinaryTrade> {
        if (this.processError) {
            try {
                const result = await this.actor.placeBinaryTrade(arg0, to_candid_TradeDirection_n20(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_BinaryTrade_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeBinaryTrade(arg0, to_candid_TradeDirection_n20(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_BinaryTrade_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeOrder(arg0: OrderRequest): Promise<OrderConfirmation> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_OrderRequest_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_OrderConfirmation_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_OrderRequest_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_OrderConfirmation_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchCoins(arg0: string): Promise<Array<Coin>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCoins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCoins(arg0);
            return result;
        }
    }
    async updateUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUsername(arg0);
            return result;
        }
    }
}
function from_candid_BinaryTrade_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BinaryTrade): BinaryTrade {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_OrderConfirmation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderConfirmation): OrderConfirmation {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_OrderKind_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderKind): OrderKind {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TradeDirection_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeDirection): TradeDirection {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TradeResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TradeResult): TradeResult {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coinSymbol: string;
    totalCost: number;
    orderKind: _OrderKind;
    orderType: _OrderType;
    timestamp: bigint;
    price: number;
    amount: number;
}): {
    coinSymbol: string;
    totalCost: number;
    orderKind: OrderKind;
    orderType: OrderType;
    timestamp: bigint;
    price: number;
    amount: number;
} {
    return {
        coinSymbol: value.coinSymbol,
        totalCost: value.totalCost,
        orderKind: from_candid_OrderKind_n16(_uploadFile, _downloadFile, value.orderKind),
        orderType: from_candid_OrderType_n18(_uploadFile, _downloadFile, value.orderType),
        timestamp: value.timestamp,
        price: value.price,
        amount: value.amount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    result: _TradeResult;
    direction: _TradeDirection;
    coinSymbol: string;
    profitLoss: number;
    durationSeconds: bigint;
    timestamp: bigint;
    amount: number;
    profitPercent: number;
}): {
    id: bigint;
    result: TradeResult;
    direction: TradeDirection;
    coinSymbol: string;
    profitLoss: number;
    durationSeconds: bigint;
    timestamp: bigint;
    amount: number;
    profitPercent: number;
} {
    return {
        id: value.id,
        result: from_candid_TradeResult_n9(_uploadFile, _downloadFile, value.result),
        direction: from_candid_TradeDirection_n11(_uploadFile, _downloadFile, value.direction),
        coinSymbol: value.coinSymbol,
        profitLoss: value.profitLoss,
        durationSeconds: value.durationSeconds,
        timestamp: value.timestamp,
        amount: value.amount,
        profitPercent: value.profitPercent
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    win: null;
} | {
    lose: null;
}): TradeResult {
    return "win" in value ? TradeResult.win : "lose" in value ? TradeResult.lose : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    long: null;
} | {
    short: null;
}): TradeDirection {
    return "long" in value ? TradeDirection.long : "short" in value ? TradeDirection.short : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limit: number;
} | {
    market: null;
}): {
    __kind__: "limit";
    limit: number;
} | {
    __kind__: "market";
    market: null;
} {
    return "limit" in value ? {
        __kind__: "limit",
        limit: value.limit
    } : "market" in value ? {
        __kind__: "market",
        market: value.market
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): OrderType {
    return "buy" in value ? OrderType.buy : "sell" in value ? OrderType.sell : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderConfirmation>): Array<OrderConfirmation> {
    return value.map((x)=>from_candid_OrderConfirmation_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BinaryTrade>): Array<BinaryTrade> {
    return value.map((x)=>from_candid_BinaryTrade_n7(_uploadFile, _downloadFile, x));
}
function to_candid_OrderKind_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderKind): _OrderKind {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_OrderRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderRequest): _OrderRequest {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_TradeDirection_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): _TradeDirection {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    coinSymbol: string;
    orderKind: OrderKind;
    orderType: OrderType;
    amount: number;
}): {
    coinSymbol: string;
    orderKind: _OrderKind;
    orderType: _OrderType;
    amount: number;
} {
    return {
        coinSymbol: value.coinSymbol,
        orderKind: to_candid_OrderKind_n24(_uploadFile, _downloadFile, value.orderKind),
        orderType: to_candid_OrderType_n26(_uploadFile, _downloadFile, value.orderType),
        amount: value.amount
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TradeDirection): {
    long: null;
} | {
    short: null;
} {
    return value == TradeDirection.long ? {
        long_: null
    } : value == TradeDirection.short ? {
        short_: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "limit";
    limit: number;
} | {
    __kind__: "market";
    market: null;
}): {
    limit: number;
} | {
    market: null;
} {
    return value.__kind__ === "limit" ? {
        limit: value.limit
    } : value.__kind__ === "market" ? {
        market: value.market
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    buy: null;
} | {
    sell: null;
} {
    return value == OrderType.buy ? {
        buy: null
    } : value == OrderType.sell ? {
        sell: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
